### ISSUE TITLE
Minitest 5, no Rails

### ISSUE THREAD

**Issue by wvanbergen** [mattheworiordan/capybara-screenshot#110]
Just a FYI, I was trying to use this on a project that uses Minitest 5, and no Rails.

I ended up adding this to my **test_helper.rb** make it work:

``` ruby
require 'capybara-screenshot'

module Minitest::CapybaraScreenshot
  def before_setup
    super
    Capybara::Screenshot.final_session_name = nil
  end

  def after_teardown
    super
    if self.class.ancestors.include?(Capybara::DSL)
      if Capybara::Screenshot.autosave_on_failure && !passed?
        Capybara.using_session(Capybara::Screenshot.final_session_name) do
          filename_prefix = self.location
          saver = Capybara::Screenshot::Saver.new(Capybara, Capybara.page, true, filename_prefix)
          saver.save
          saver.output_screenshot_path
        end
      end
    end
  end
end

class Minitest::Test
  include Minitest::CapybaraScreenshot
end
```

This will enable screenshotting for every test class that has `Capybara::DSL included`

**Comment by mattheworiordan** [comment]
@wvanbergen thanks for the note.  Unfortunately I don't have time right now to add support for Minitest 5 without Rails, but if you do have a chance please do create a PR to help others like yourself, I would appreciate it.
