### ISSUE TITLE
Manual screenshots with Cucumber not all getting saved.

### ISSUE THREAD

**Issue by streetlogics** [mattheworiordan/capybara-screenshot#112]
For my use case, we are using cucumber + timecop to freeze time for some of our tests.  This causes issues when trying to manually call `screenshot_and_open_image`.  After some debugging, I realized the issue is because the timestamp is getting "frozen" by timecop, which trickles down to this project.  The way this issue surfaces is that multiple calls to `screenshot_and_open_image` only appears to create 1 screenshot, when in actuality, it's trying to create many, it's just that they're all using the same filename, so only 1 actually gets stored.

**Comment by mattheworiordan** [comment]
This was merged
