### ISSUE TITLE
I would like the option to not create the default html file for cucumber when taking screenshot on failure

### ISSUE THREAD

**Issue by scalixte-mdsol** [mattheworiordan/capybara-screenshot#114]
When running tests with cucumber with automated save on failure feature set, both the image an a corresponding html file are saved. However, I would like the options:
1) Save Image only (no HTML)
2) Embed Image into HTML (No Image file)
3) Embed Image into HTML (with Image file)

**Comment by mattheworiordan** [comment]
Sure, sounds like a useful feature, feel free to do a PR and I'll review.

**Comment by mattheworiordan** [comment]
No PR, so I am closing.  Feel free to do a PR if you want this feature
