### ISSUE TITLE
Compatibility branch for ruby 1.8 not working

### ISSUE THREAD

**Issue by zedtux** [mattheworiordan/capybara-screenshot#117]
We have a Rails 2.3 application, running the latest Ruby 1.8 version with Capybara 1.1.4. We tried to use the capybara-screenshot gem but it is not working.

First issue was about loading issue (solved with the PR https://github.com/mattheworiordan/capybara-screenshot/pull/116).

Now when a test runs and fails, nothing happen because the `Capybara.current_path` is blank and [this guard condition](https://github.com/mattheworiordan/capybara-screenshot/blob/ruby-1.8-support/lib/capybara-screenshot/saver.rb#L14) is rejecting us.

Also I have checked the `Capybara.page.body` and `Capybara.page.source` and both are fine when I have a `After` in my application `env.rb` but in the [cucumber.rb](https://github.com/mattheworiordan/capybara-screenshot/blob/ruby-1.8-support/lib/capybara-screenshot/cucumber.rb) file it is blank.

Of course my failing test is on a `Then I should see ...` so there is a page with content to be checked so it should be possible to at least have the html file.

**Comment by mattheworiordan** [comment]
Sorry to hear that, but I have no intention personally of supporting Ruby 1.8.  Are you using the 1.8 branch though?  See https://github.com/mattheworiordan/capybara-screenshot/tree/ruby-1.8-support

If you want to add support for this legacy app then please go ahead.

**Comment by zedtux** [comment]
> Are you using the 1.8 branch though?

Yes I do.

As described in my issue, there's no errors, the issue is that nothing is generated (no HTML, no image).

Then let's close this issue as I don't have the time too.
