### ISSUE TITLE
WebkitDebug uses render instead of save_screenshot

### ISSUE THREAD

**Issue by JanStevens** [mattheworiordan/capybara-screenshot#119]
Hello,

I noticed in `capybara-screenshot.rb` that the following drivers are default defined:

```ruby
register_driver(:webkit) do |driver, path|
    if driver.respond_to?(:save_screenshot)
      driver.save_screenshot(path, webkit_options)
    else
      driver.render(path)
    end
  end

  register_driver(:webkit_debug) do |driver, path|
    driver.render(path)
  end
```

Shouldnt the webkit_debug alos have the same options? Right now taking screenshots with webkit_debug results in a `render` error since webkit driver does not support the render option and uses `save_screenshot` instead.

Regards

**Comment by mattheworiordan** [comment]
Ah yes, seems that when the `save_screenshot` option was added it was not added to webkit_debug as well.  I'll get this fixed, thanks for notifying me.
