### ISSUE TITLE
Upload to Amazon S3?

### ISSUE THREAD

**Issue by mwise** [mattheworiordan/capybara-screenshot#120]
Would you be interested in a PR that adds support for uploading screenshots to S3 instead of (or perhaps in conjunction with) saving them to the filesystem. Our team thought this might be useful and we were planning to roll something up to that effect. If it's something you'd want in capybara-screenshot, then I'll fork it and see what we can do. Our initial spike looks promising. 

If S3 uploads are outside the scope of this project (it would likely add a dependency on the `aws-sdk` gem), then I'll probably create a small gem that depends on capybara-screenshot instead.  

Please just let me know either way, and I'll keep you updated on our progress. Thanks!

**Comment by mattheworiordan** [comment]
@mwise interestingly in our team we used to do this using a very simple command line S3 tool so I do think it's quite possibly a feature that would be useful for people.  I would love to merge it in if you give it a go.  Shout if you need any assistance.

**Comment by mwise** [comment]
@mattheworiordan I'm having some difficulty running the spec suite. I've run `bundle install` and `appraisal install`, but when I try to run `appraisal "bundle exec rspec && bundle exec cucumber"` I get the following error message. I've never used `appraisal` before, so it's probably something simple that I've missed.

```
→ appraisal "bundle exec rspec && bundle exec cucumber"
>> BUNDLE_GEMFILE=/Users/mwise/projects/open-source/capybara-screenshot/gemfiles/rspec.2.14.gemfile bundle\ exec\ rspec\ \&\&\ bundle\ exec\ cucumber
sh: bundle exec rspec && bundle exec cucumber: command not found
```

Does that look familiar to you?  I can run `appraisal bundle exec rspec` ok (although some spinach tests fail). When I try to run just the cukes via appraisal, I get:
```
appraisal bundle exec cucumber
>> BUNDLE_GEMFILE=/Users/mwise/projects/open-source/capybara-screenshot/gemfiles/rspec.2.14.gemfile bundle exec cucumber
No such file or directory - features. Please create a features directory to get started. (Errno::ENOENT)
```

I'm wondering if these are RVM/gemset issues - I have `.ruby-version` and `.ruby-gemset` files in the project folder, so perhaps that is confusing things. I'd love to not pollute my global gem set with all the gems that the `appraisal install` installs.

Any thoughts?

**Comment by mattheworiordan** [comment]
@mwise, why are you trying to run Cucumber?  The test suite is built with RSpec only and it in turn spins up the necessary test suite within Spec.  

Personally I would not use appraisal at all and simply run the test suite against one set of gems and one ruby version, and then once you have that working, you can create the PR and see what Travis CI reveals in terms of specific Ruby / Gem version issues, see https://travis-ci.org/mattheworiordan/capybara-screenshot for an example.

**Comment by mwise** [comment]
Ahh ok cool, that was my plan. I was just running the cukes because of the `appraisal "bundle exec rspec && bundle exec cucumber"` from the README. I'll roll with the RSpec approach and let CI run the full suite. Thanks!

**Comment by mwise** [comment]
Also, FYI the spinach failures were colorize-related, and they were fixed when I merged in the latest master.

**Comment by mwise** [comment]
@mattheworiordan quick question, and sorry for the spam this morning: would you prefer this to be architected so that the filesytem/s3 saving is either/or, or would you want the s3 storage to be opt-in and additive?  Also, would you prefer the images uploaded on-demand or in batch at the end of the suite (as appropriate)?

**Comment by mattheworiordan** [comment]
I would prefer that the S3 option is just that, an additional option to upload the file as well.  You could then perhaps add another option to delete the file after it is successfully uploaded if you wish.

I think personally a batch upload is better, that is what we did, however it does then mean you can't be 100% certain that the URL in the report will match the S3 path given the file is not yet uploaded. 

I am happy for you to take whatever approach you think is best.

Thanks again for contributing.

**Comment by mattheworiordan** [comment]
@mwise do you think you will do a PR, or should I close this now?

**Comment by mwise** [comment]
I'm not currently working in Ruby-land, so please feel free to close this out.

**Comment by chendrix** [comment]
I've actually got a fork/PR brewing chendrix/capybara-screenshot@84027e70ad0e49fe8fa435dd46527340f278d319 

I've tested it manually by running some capybara tests from another project I'm working on and verified it successfully added it to the S3 bucket. I'm just missing some test back-fill, and was wondering how you wanted me to approach the integration-y nature of this feature, @mattheworiordan?

**Comment by mattheworiordan** [comment]
Hi @chendrix, exciting.
Personally I would simply stub out the AWS SDK as you know that works, and so long as you test it locally and it works, and then you stub out the respective upload methods of the SDK, that should suffice.

One thing however that concerns me is that you've included the `aws-sdk` as a dependency of `capybara-screenshot`.  I really don't think this will work as it is unnecessary overhead for most users who simply don't need this.  I can think of two approaches you could take:

* Specify that this library expects the `aws-sdk` to be available, so the Gemfile for app that uses `capybara-screenshot` must set `aws-sdk` as a dependency.
* Move the S3 upload into a separate Gem that adds this functionality.

What do you think is best?

**Comment by chendrix** [comment]
I think the easiest thing is to move the requires into a single file and only require the s3 saver if s3 is configured. Then show an example of how to add "aws-sdk" as a sibling gem dependency.




I think long term pulling it out into a gem is a great idea, but would require some collaboration and work done to provide plugin/configuration points.

**Comment by mattheworiordan** [comment]
Sure, sounds good
