### ISSUE TITLE
The Pruner Ate My Home Directory

### ISSUE THREAD

**Issue by mgarriott** [mattheworiordan/capybara-screenshot#122]
During a round of testing, I was playing around changing my `Capybara.save_and_open_page_path` and set it to my home directory. Unwittingly, I also had set the pruning strategy to `Capybara::Screenshot.prune_strategy = { keep: 10 }`. After running my tests with these settings, I began seeing a bunch of bizarre errors and realized that several of my subdirectories under home had been removed.

For the sake of anyone else who may make this mistake, you might consider relaxing the `rm` commands, eg: https://github.com/mattheworiordan/capybara-screenshot/blob/master/lib/capybara-screenshot/pruner.rb#L43. I cannot see why the `rm` statements should be recursive, and I certainly can't see why they should be forced. It may also be nice to ensure that only files beginning with the screenshot prefix should be removed, eg: `screenshot_*`.

Thanks,
-Matt

**Comment by mattheworiordan** [comment]
Sure, fixed with https://github.com/mattheworiordan/capybara-screenshot/commit/680d7339a61d81adbe872bf94109f536a5e20d20.

**Comment by mgarriott** [comment]
That should definitely help! Thanks!
