### ISSUE TITLE
I am trying to put prune strategy for capybara screenshots but it is not working

### ISSUE THREAD

**Issue by chetshah** [mattheworiordan/capybara-screenshot#125]
Capybara::Screenshot.prune_strategy = :keep_last_run
and when i print   p Capybara::Screenshot.methods prune_strategy method doesn't come up in the list.
and getting this "undefined method `prune_strategy=' for Capybara::Screenshot:Module (NoMethodError) error" when i run test.

**Comment by mattheworiordan** [comment]
@chetshah is this resolved?

**Comment by chetshah** [comment]
yeah thanks we were using older version of capybara screenshot.
