### ISSUE TITLE
Only getting html printout

### ISSUE THREAD

**Issue by CID-DAVE** [mattheworiordan/capybara-screenshot#129]
I am only getting the html output and not the image output
   ./features/step_definitions/organization_decision_action_steps.rb:10:in `/^I click new decision action button$/'
   features/organization_editing/organization.decision_actions.feature:15:in `And I click new decision action button'
 HTML screenshot: /vagrant/tmp/capybara/screenshot_2015-05-21-17-12-00.551.html

I am using capybara with poltergeist

**Comment by CID-DAVE** [comment]
It tells me the default driver is rack_test even though I have poltergeist specified in configuration. Any ideas?

**Comment by mattheworiordan** [comment]
@CID-DAVE, sorry, no, what versions of each are you suing?  Can you replicate the issue with a simple example so that I can look into it?

**Comment by CID-DAVE** [comment]
thanks for getting back.  I believe this has been resolved.
