### ISSUE TITLE
Support for Fuubar

### ISSUE THREAD

**Issue by lacco** [mattheworiordan/capybara-screenshot#135]
Is there any interest in getting ```capybara-screenshot``` working with https://github.com/thekompanee/fuubar ? I added the following line to ```spec_helper.rb``` which made the integration work:

```ruby
Capybara::Screenshot::RSpec::REPORTERS["Fuubar"] = Capybara::Screenshot::RSpec::TextReporter
```

In case we want to add it to ```capybara-screenshot``` core, I can make a separate pull request...

**Comment by mattheworiordan** [comment]
I am not sure why this is needed?  I don't really follow as Fuubar looks like an RSpec reporter?

**Comment by lacco** [comment]
I am a little unsure about the difference of formatter vs reporter, I only observed that using ```--format Fuubar``` for RSpec breaks the injection of ```capybara-screenshot``` in https://github.com/mattheworiordan/capybara-screenshot/blob/master/lib/capybara-screenshot/rspec.rb#L86 . Adding ```Fuubar```  to ```Capybara::Screenshot::RSpec::REPORTERS``` fixed the issue for me, so that screenshot links are now included in my Fuubar-reported failures.

**Comment by mattheworiordan** [comment]
@lacco well I am happy to merge in a PR that adds Fuubar support, but unfortunately this is not something I am familiar with myself so won't be spending time on this myself.
