### ISSUE TITLE
Does this work in Minitest Spces?

### ISSUE THREAD

**Issue by DarynHolmes** [mattheworiordan/capybara-screenshot#136]
I can't seem to get this working in Minitest specs. Is it supported in Minitest specs?

**Comment by DarynHolmes** [comment]
I have got screenshot_and_open_image to work. However it does not save an image when the test fails...

**Comment by DarynHolmes** [comment]
I have got screenshot_and_open_image to work. However it does not save an image when the test fails...

**Comment by mattheworiordan** [comment]
Hi @DarynHolmes, can you provide an example?  We do have some minitest tests at https://github.com/mattheworiordan/capybara-screenshot/blob/master/spec/feature/minitest_spec.rb

**Comment by matt-riemer** [comment]
I had to use the after_teardown hook in order to get screenshots to work after failing in minitest

In my `test_helper.rb`:

```
....
require 'capybara/webkit'
require 'capybara-screenshot/minitest'

class ActionDispatch::IntegrationTest
  include Capybara::DSL
  include Capybara::Assertions
  include Capybara::Screenshot::MiniTestPlugin

  def setup # Called before every test
  end

  def teardown # Called after every single test
  end

  def after_teardown # I reset sessions here so capybara-screenshot can still make screenshots when tests fail
    super(); Capybara.reset_sessions!
  end
end
```

**Comment by mattheworiordan** [comment]
@matt-riemer any chance you could try and integrate that into this gem?  I am really pushed for time at the moment so can't see myself, and don't work with Minitest day to day...

**Comment by DarynHolmes** [comment]
I am using Minitest specs, which is a bit different to the example @matt-riemer gave above. This is a small extract from the Minitest GitHub home page:

```
require "minitest/autorun"

describe Meme do  
  describe "when asked about cheeseburgers" do
    it "must respond positively" do
      @meme.i_can_has_cheezburger?.must_equal "OHAI!"
    end
  end
end 
```
Maybe the issue is that I was not using `include Capybara::Screenshot::MiniTestPlugin`. I will try this again later and let you know if I made progress...

**Comment by DarynHolmes** [comment]
I tried again and it still does not seem to take screenshots when the test fails. This is the code:

```
require_relative '../spec_helper'
include Custom
include Capybara::DSL
include Capybara::Screenshot::MiniTestPlugin

describe 'Login page' do
  def setup
    ensure_logged_out
  end

  it 'should show the summary page after logging' do
    screenshot_and_save_page
    verify_successful_login('abc', 'xyz')
  end
end
```

**Comment by DarynHolmes** [comment]
I'm not sure which is the correct way to include a mixin with Minitest Specs?

**Comment by matt-riemer** [comment]
I will try to submit a PR in the near future

minitest, minitest spec, rspec, capybara, rack_test...yay for standards :)

**Comment by DarynHolmes** [comment]
Is `ActionDispatch::IntegrationTest` only for Rails development? 
Is there a fix for non-Rails solution?

**Comment by Mavvie** [comment]
@matt-riemer thanks for this. Worked perfectly.

**Comment by mattheworiordan** [comment]
> I'll try to throw together a PR now.

**Comment by Mavvie** [comment]
Hey to be clear, do you mean adding some info about the `MiniTestPlugin` to the readme, or doing the Capybara reset in the after_teardown block? Not sure if you saw my edit.

**Comment by glaszig** [comment]
the problem here may be that the minitest plugin will only work if `ActionDispatch::IntegrationTest` is in the test's ancestor tree. see my comment on d7ccd7568.

**Comment by glaszig** [comment]
just found another gotcha. capybara-screenshot doesn't like `Capybara.reset_session!` being called before it takes a screenshot (because it needs the current browser session, obviously). now, some gems recommend calling `Capybara.reset_session!` during `#teardown` or add such callbacks themselves.

one example of such gem is [`minitest-capybara`](https://github.com/wojtekmach/minitest-capybara/blob/33d95a76b281debd36474a4be22a745c7a264b53/lib/minitest/capybara.rb#L32-L35). and even [capybara itself](https://github.com/jnicklas/capybara#using-capybara-with-testunit) poses such instructions.

sadly, `Capybara::Screenshot::MiniTestPlugin` adds its screenshot logic with an `#after_teardown` callback. you've guessed it. when `#after_teardown` is called, all other `#teardown` callbacks -- including that of minitest-capybara, which resets the session -- have been run.

but since we are in ruby-land, a proper monkey patch is not far away :smile:

```rb

module Capybara
  module Screenshot
    module MiniTestPlugin
      alias before_teardown after_teardown
      remove_method :after_teardown
    end
  end
end
```

put this into your `test_helper.rb` and you should be good to go.

if this can be assumed safe, @mattheworiordan, i can pr this.

**Comment by mattheworiordan** [comment]
@glaszig I think 918cd7b is a good solution, I assume you are happy for me to incorporate that as opposed to the monkey patch you have suggested above?

**Comment by glaszig** [comment]
sure. would you like it as a pr?

**Comment by mattheworiordan** [comment]
Yes please, I see you've done it.  Are you OK for me to close this issue and work with the PR now then?

**Comment by glaszig** [comment]
yes. all other participants in this issue should try the new release and open a new issue if the original problem isn't solved with this, i would say.

**Comment by mattheworiordan** [comment]
Everyone, I am closing this issue now and merging in @glaszig's work.  You've had your chance :)
