### ISSUE TITLE
Failing to take screenshot; error is "rack-test requires a rack application"

### ISSUE THREAD

**Issue by duncan-bayne** [mattheworiordan/capybara-screenshot#140]
I've added capybara-screenshot to my application, but it's failing to take screenshots upon Cucumber failures with the following error: `rack-test requires a rack application, but none was given (ArgumentError)`

Relevant Gems:

```
capybara-screenshot (1.0.11)
capybara (2.5.0)
launchy (2.4.3)
```

This is running on ruby `2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]`.  The app in question isn't a Rails app, but it does use Rack.

**Comment by duncan-bayne** [comment]
Upgrading to Cucumber 2.1.0 didn't fix it.

**Comment by sshakil** [comment]
Also getting this error with Minitest:

```
WARN: Screenshot could not be saved. `page.current_path` raised exception: #<ArgumentError: rack-test requires a rack application, but none was given>.
```

Test:

```ruby
require 'test_helper'

class CreateCategoriesTest < ActionDispatch::IntegrationTest
  include Capybara::Screenshot::MiniTestPlugin

  test "get new category form and create category" do
    get new_category_path
    assert_template 'categories/new'
    assert_difference 'Category.count', 1 do
      post categories_path, params: {category: {name: 'sports'}} # create action is post
    end
    binding.pry
    Capybara::Screenshot.screenshot_and_open_image
    assert_template 'categories/index'
    assert_match "sports", response.body
  end
end
```

Is some Capybara-specific configuration required for this to work out-of-the-box with Minitest integration tests?

**Comment by mattheworiordan** [comment]
@sshakil and @duncan-bayne sorry to hear you're hitting issues.  Sounds like in the first case the issue is Capybara is not installed, so that should fix @duncan-bayne's issue.  In the second case, I am not sure what has changed @sshakil that would cause this.  Unfortunately I am going to have to leave this for you to debug as I don't have time right now to maintain this library for environments I don't work in myself.  Sorry :(

**Comment by duncan-bayne** [comment]
Never had the chance to debug this.  Been silent for three years, happy to close?
