### ISSUE TITLE
PNG only shows a "This Webpage Not Found" response with Selenium Chrome driver

### ISSUE THREAD

**Issue by adsteel** [mattheworiordan/capybara-screenshot#141]
On error, the HTML snapshot is correct, but the PNG image only shows this:

![image](https://cloud.githubusercontent.com/assets/4186462/10294739/61193480-6b79-11e5-8452-9ce41df7b295.png)

This is for a Rails 4.2, Ruby 2.1.4 application.

Gemfile.lock

```
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-screenshot (1.0.11)
      capybara (>= 1.0, < 3)
      launchy
    chromedriver-helper (1.0.0)
      archive-zip (~> 0.7.0)
      nokogiri (~> 1.6)
    capybara-webkit (1.6.0)
      capybara (>= 2.3.0, < 2.5.0)
      json
    selenium-webdriver (2.46.2)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
```

support/env.rb

```
Cucumber::Rails::Database.javascript_strategy = :truncation

Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end

Capybara::Screenshot.register_driver :chrome do |driver, path|
end

Capybara.javascript_driver = :chrome
```

When I try to manually run the screenshot, I get this error:

`
No application found to handle '/Users/rails_app/tmp/capybara/screenshot_2015-10-05-16-03-26.171.png' (Launchy::ApplicationNotFoundError)
`

Driver during this error is chrome.

```
puts Capybara.current_driver
# => chrome
```

When I switch to the driver to `:selenium` and its default browser, the issue goes away and the correct image is generated.

**Comment by mattheworiordan** [comment]
@adsteel sorry, I'd love to help, but I'm pretty overloaded at the moment.  This does not sound like a `capybara-screenshot` gem issue though, it sounds more like the Selenium Chrome drive is unable to create screenshots correctly. If you cannot manually create a screenshot, then that is definitely a Selenium Chrome issue.  Can you try and isolate where the problem is exactly and I will see if I can make some time to resolve if it's an issue with this gem.

**Comment by adsteel** [comment]
@mattheworiordan I was able to fix this by adding the following to my config file.

```
Capybara::Screenshot.register_driver :chrome do |driver, path|
  driver.save_screenshot(path) # added this line
end
```

May be worth putting in the readme?
