### ISSUE TITLE
Screenshots are not taken when using multiple windows

### ISSUE THREAD

**Issue by Intrepidd** [mattheworiordan/capybara-screenshot#143]
Hi,

When I use the capybara window api, with methods such as `open_new_window`, `switch_to_window`, et al, in the case of an error, no screenshots are saved.

Is this intended behavior ?

Thanks !

**Comment by mattheworiordan** [comment]
I am unfortunately not clear on what you mean, or why that would have an impact on things.  If you can provide a suitable code example, or ideally, a PR to address the issue, that would be appreciated

**Comment by wallyaltman** [comment]
I have found that when I do this:

```ruby
new_tab = window_opened_by { some_link_opening_a_new_tab.click }
within_window(new_tab) do
  page.find("#non_existent_element")
end
```

the automatically-generated screenshots will show the original tab and not the tab where the exception happened.

I'm working around the issue by doing this:

```ruby
def inside_tab(tab)
  within_window(tab) do
    begin
      yield if block_given?
    rescue Capybara::ElementNotFound
      # Manually save the page, then re-raise the exception.
      screenshot_and_save_page
      raise
    end
  end
end
```

and then this:

```ruby
new_tab = window_opened_by { some_link_opening_a_new_tab.click }
inside_tab(new_tab) do
  page.find("#non_existent_element")
end
```

**Comment by dreyks** [comment]
yes. happening to me too: when capybara-screenshot takes its screenshot (after example failure) the `within_window` has already switched back to the original tab

**Comment by dreyks** [comment]
made https://github.com/mattheworiordan/capybara-screenshot/pull/245

**Comment by cgunther** [comment]
@Intrepidd @wallyaltman check out #287 for a fix
