### ISSUE TITLE
Docs for Custom screenshot directory Wrong

### ISSUE THREAD

**Issue by sshaw** [mattheworiordan/capybara-screenshot#144]
Docs say:

> By default screenshots are saved into $APPLICATION_ROOT/tmp/capybara

But `Capybara.save_and_open_page_path` [defaults to `Dir.pwd`](http://www.rubydoc.info/gems/capybara/Capybara.configure). It only defaults to `tmp/capybara` when running under Rails.

**Comment by sshaw** [comment]
You should also mention the [special handling](https://github.com/mattheworiordan/capybara-screenshot/blob/v1.0.11/lib/capybara-screenshot.rb#L54-L64) for Sinatra, Padrino, and Rails.

**Comment by mattheworiordan** [comment]
Thanks for the feedback, fancy issuing a PR to address this?

**Comment by sshaw** [comment]
I'll throw something together for this and #145.
