### ISSUE TITLE
Screenshot.capybara_root Should Not Call Padrino.root With an Absolute Path

### ISSUE THREAD

**Issue by sshaw** [mattheworiordan/capybara-screenshot#145]
My config set `Capybara.save_and_open_page_path = Padrino.root('tmp/capybara')`.

Under Padrino, `Screenshot.capybara_root` [passes `capybara_tmp_path` to `Padrino.root`](https://github.com/mattheworiordan/capybara-screenshot/blob/v1.0.11/lib/capybara-screenshot.rb#L54-L64), which will always append its argument to Padrino's root directory. This causes screenshots to be saved to the wrong path.

```
padrino [0.12.5] (itunes_store_transporter_web)$ Capybara.save_and_open_page_path
=> "/Users/sshaw/code/ruby/itunes_store_transporter_web/tmp/capybara"
padrino [0.12.5] (itunes_store_transporter_web)$ Padrino.root Capybara.save_and_open_page_path
=> "/Users/sshaw/code/ruby/itunes_store_transporter_web/Users/sshaw/code/ruby/itunes_store_transporter_web/tmp/capybara"
```

**Comment by mattheworiordan** [comment]
Ah, I don't use Padrino, would you mind issuing a PR that fixes this issue as you can test the solution yourself?
