### ISSUE TITLE
spinach add in

### ISSUE THREAD

**Issue by chabgood** [mattheworiordan/capybara-screenshot#151]
I have added, require 'capybara-screenshot/spinach'  to the env file and I get:
cannot load such file -- capybara-screenshot/spinach (LoadError)

**Comment by mattheworiordan** [comment]
Well it's definitely there, https://github.com/mattheworiordan/capybara-screenshot/blob/master/lib/capybara-screenshot/spinach.rb

We will need more info to work out what is wrong, are you sure the capybara-screenshot gem installed?

**Comment by chabgood** [comment]
Yes it is installed.

gem list --local | grep capy
capybara (2.5.0)
capybara-email (2.4.0)
capybara-screenshot (1.0.11)

**Comment by mattheworiordan** [comment]
What happens when you `require "capaybara-screenshot"`

**Comment by chabgood** [comment]
Interesting, I get:

Saved file /Users/chabgood/projects/me/registeryourhorse/tmp/capybara/screenshot_2016-01-18-19-34-34.324.html
Rack::Test capybara driver has no ability to output screen shots. Skipping.

All of the images are missing in the saved file.

**Comment by mattheworiordan** [comment]
That's because you are using the Rack driver i.e. not a headless browser, so not sure what you expected to capture?  Also, not sure how this relates to the spinach issue unfortunately.  Can you try `require "capybara-screenshot/capybara-screenshot/spinach"` and also `require "capybara-screenshot/lib/spinach"` to see if those work?

**Comment by chabgood** [comment]
Thanks, neither one of those commands worked, it errored out.

cannot load such file -- capybara-screenshot/capybara-screenshot/spinach (LoadError)

cannot load such file -- capybara-screenshot/lib/spinach (LoadError)

FYI, 'require 'capybara-screenshot''  works it is just that when i open the file all of the images are missing, a bit odd.

**Comment by mattheworiordan** [comment]
> FYI, 'require 'capybara-screenshot'' works it is just that when i open the file all of the images are missing, a bit odd.

You mean the HTML file?  If so, that is not a capybara-screenshot issue, we only call the driver's create screen shot or save HTML method, it is up to the driver to ensure that the HTML has relative paths or the PNG etc is valid
