### ISSUE TITLE
Unable to get screenshot on failure to work.  

### ISSUE THREAD

**Issue by colinjcahill** [mattheworiordan/capybara-screenshot#154]
I'm really not sure what I'm doing wrong here, but I've pared everything way down and still can't seem to get screenshot_on_failure to work correctly.

Here's a very small setup which I believe should work.  I'm a bit of a noob so I apologize if there's something obvious I'm missing, but I've tried a lot of options.

```
require 'rspec'
require 'capybara'
require 'selenium-webdriver'
require 'capybara-screenshot'
require 'capybara/poltergeist'
require 'capybara/rspec'
require 'capybara-screenshot/rspec'

Capybara.default_driver = :poltergeist
Capybara::Screenshot.autosave_on_failure = true
Capybara::Screenshot::RSpec.add_link_to_screenshot_for_failed_examples = true


RSpec.describe "Screenshot Test" do
  context 'when this happens' do
    it 'goes like this' do
    @session = Capybara::Session.new Capybara.current_driver
    Capybara.app_host = 'https://www.google.com/'
    @page = Capybara.page
    @page.visit Capybara.app_host
    puts "This is the page: #{@page.current_url}"
    expect(@page.current_url).to eq("zombies.com")
    end
  end
end

```

here's the Gemfile for the above test:

```
source 'https://rubygems.org'

gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'poltergeist'
gem 'capybara-screenshot'
gem 'pry'
```

If I drop in a binding.pry, I am correctly able to use either `Capybara::Screenshot.screenshot_and_save_page` or `Capybara::Screenshot.screenshot_and_open_image`.

This issue fails equally when swapping out the driver from `:poltergeist` to `:selenium`.

So I guess I'm wondering the following:
- Is Capybara-Screenshot set up to work on standalone test suites?  Most examples I'm seeing seem to be within the context of a Rails or Sinatra app.
- Is it expected that this gem will work with the latest versions of Capybara and RSpec?  

Thanks!

**Comment by mattheworiordan** [comment]
This should work with a standalone test suite, can you add a debugger to https://github.com/mattheworiordan/capybara-screenshot/blob/master/lib/capybara-screenshot/rspec.rb#L51 and see if it's reaching that point?

**Comment by Sinetheta** [comment]
Hi @mattheworiordan I ended up here because of the same issue. It seems that during `after_failed_example` `Capybara.page.current_url == "about:blank"` while just _before_ the failure it's what I expect `"http://127.0.0.1:63841/cart"`, a time when I can take screenshots manually.

I'm not yet sure _why_ the page has changed after the failure, but it's certainly preventing a screenshot from being made.
