### ISSUE TITLE
After upgrade screenshots are saved to application root

### ISSUE THREAD

**Issue by samstickland** [mattheworiordan/capybara-screenshot#170]
Hi,

After upgrading to capybara-screenshot 1.0.12 (with Rails), my screenshots are now being saved to the application root directory, rather than `tmp/capybara`

It's possible that this is also a capybara issue as we upgraded to 2.7.0 at the same time?

**Comment by AntonTrapp** [comment]
I just ran into the same issue that my screenshots were generated in the project root directory **after a capybara upgrade (screenshot was fixed at 1.0.3)**. What was worse: the prune did erease my root project directory :D - after upgrading screenshot to 1.0.12 at least my project is not deleted during every test :) - but something in Capybara must have changed that has side effects on the screenshot gem. Hope this info is helpful to reproduce the bug.

**Comment by AntonTrapp** [comment]
I think it's a capybara bug and there is a **workaround** (it's working for me). Reason:

If you set the path for Capybara screenshots explicitely:

```ruby
Capybara.save_and_open_page_path = "tmp/capybara"
```

You get a deprecation warning that you should use **Capybara.save_path** instead (which then removes the deprecation warning but completely ignores the path) but **it stores them in the directory you specify**.

P.S.: If the save_and_open_page_path is really deprecated the documentation in this project should be updated.

**Comment by AntonTrapp** [comment]
"capybara-screenshot passes absolute paths to capybara, if it's ignoring save_path it's because it hasn't yet been updated to be compatible with capybara 2.7" (from https://github.com/jnicklas/capybara/issues/1688)

**Comment by mattheworiordan** [comment]
Sorry about this @AntonTrapp and @samstickland.  I have asked for a comment on what's changed to save me trawling through the changes on Capybara.  Hopefully I'll get a quick response and can apply a quick patch update to `capybara-screenshot`

**Comment by mattheworiordan** [comment]
I believe this is related to https://github.com/mattheworiordan/capybara-screenshot/issues/164 although not looked in detail.  I will investigate further soon...

**Comment by AntonTrapp** [comment]
No need to rush, as I mentioned above the path can be set manually as a workaround!

**Comment by ronwsmith** [comment]
Running into this issue now too.

**Comment by mokolabs** [comment]
Me too.

**Comment by veera** [comment]
+1

**Comment by mattheworiordan** [comment]
Would anyone of you experiencing this issue be able to spare some time for a quick fix that I could merge in?  I have not had time unfortunately to look into this in detail.

**Comment by AntonTrapp** [comment]
As I mentioned above, setting the Capybara.save_and_open_page_path is working for me at the moment, if this is still an issue in 3-4 weeks I can try to help, now I am very short on time... :(

**Comment by mokolabs** [comment]
@mattheworiordan sure, i can help!

**Comment by f3ndot** [comment]
@mokolabs thanks for taking a boo. See #164 for more context as potential root cause

**Comment by heliosam** [comment]
@mattheworiordan still needing help? We just hit this problem

**Comment by mattheworiordan** [comment]
Sorry @heliosam, not had time, flat out on my business www.ably.io.  I am happy to consider a PR that will help though if you can spare the time?

**Comment by heliosam** [comment]
I can get the time to do it, let me know how can I help :-)

**Comment by mokolabs** [comment]
@mattheworiordan did you read this yet?

> @mattheworiordan The first thing save_page and save_screenshot do is call prepare_path passing in the filename/path passed to them and the default extension types (html/png). If Capybara.save_path is defined Capybara should handle relative filenames correctly and you should be able to just pass a relative filename/path and it should save in the right place (or use Capybara.save_path to build an absolute path), if save_path is not defined and the previous Capybara.save_and_open_page_path is non nil you need to do what you were previously doing.

In my case, manually setting `Capybara.save_path` doesn't work. No matter what value I use, `Capybara.save_path` is nil once my Rails app boots app. Maybe that's another clue. Who knows?

But I do think you're probably our only hope of getting this fixed!

**Comment by axlekb** [comment]
I'm not seeing this issue on  `capybara (2.7.1)` and     `capybara-screenshot (1.0.13)`.  Latest versions of both as of this time.

**Comment by AntonTrapp** [comment]
@mokolabs - have you tried `Capybara.save_and_open_page_path = "tmp/capybara"`? Brings you a deprecation warning, but worked for me as workaround.

**Comment by mokolabs** [comment]
@AntonTrapp yup, the workaround works for me, but i'm also interested in getting the root problem solved (if it still exits).

**Comment by mokolabs** [comment]
@AntonTrapp just updated to `capybara (2.7.1)` and `capybara-screenshot (1.0.13)` and the screenshots are being saved into `tmp/capybara` without needing to manually set a value for `Capybara.save_path`.

So does that mean this issue can now be closed?

**Comment by AntonTrapp** [comment]
sounds great, can check it tomorrow on my systems...

**Comment by mattheworiordan** [comment]
> So does that mean this issue can now be closed?

Well if the issue is resolved for everyone, would appreciate any feedback from anyone if the prob is not resolved.  Thanks everyone for bearing with me whilst I am very busy...

**Comment by gamov** [comment]
I've also removed the deprecated setting and it seems to work as expected now.

**Comment by AntonTrapp** [comment]
Can confirm that capybara 2.7.1 and capybara-screenshot 1.0.13 are working fine on 3 of my development macs without the need to set the save path manually :)

**Comment by kernow** [comment]
I can confirm that setting the path using `Capybara.save_path` now works correctly and there is no need to use any workaround. capybara (2.7.1) and capybara-screenshot (1.0.13)

**Comment by xam7247** [comment]
Yes, works with the latest of both gems and relative paths 👍

**Comment by samstickland** [comment]
+1

2016-07-21 15:16 GMT+01:00 Saumya Negi <notifications@github.com>:

**Comment by agross** [comment]
I have a different problem with capybara 2.7.1 and capybara-screenshot 1.0.13:

```ruby
::Capybara.save_path = 'build/spec/screenshots'
```

capybara-screenshots reports saved paths like this:
```
  HTML screenshot: file://build/spec/screenshots/foo.html
  Image screenshot: file://build/spec/screenshots/foo.png
```

And capybara saves the screenshot (image) to `build/spec/screenshots/foo.png` (as desired), but the HTML is saved to `build/spec/screenshots/build/spec/screenshots/foo.html` (undesired).

As far as I understand the changes (`save_and_open_page` vs. new `save_page`) the undesired behavior is correct as `file://build/spec/screenshots/foo.html` is a relative path and `save_path` needs to be appended.

**Comment by mattheworiordan** [comment]
Dare I suggest that you simply use an absolute path instead then as opposed to spending time working out the intricacies of why different versions of Capybara treat the paths differently?
