### ISSUE TITLE
Screenshot in Wingdings

### ISSUE THREAD

**Issue by esumerfd** [mattheworiordan/capybara-screenshot#172]
The screenshots on the mac look fine but run on redhat I get an image that looks like it has the wingdings font. Anyone know how to fix that?

    https://flic.kr/p/GxnvUC

**Comment by mattheworiordan** [comment]
@esumerfd this problem would be a Capybara related issue and not a `capybara-screenshot` issue. This gem does not interfere or influence how screenshots are taken.
