### ISSUE TITLE
mkmf adds Logging module v 1.0.12

### ISSUE THREAD

**Issue by arielvalentin** [mattheworiordan/capybara-screenshot#174]
I tried upgrading to the latest version of screenshot but run into this error when running cucumber tests:
`undefined method 'html_safe' for #<IO:<STDOUT>> (ActionView::Template::Error)`

The error comes from this block of code:
```
  6      - if defined?(message) && message.present?
  7           .short
  8             = sanitize_and_auto_link(message.html_safe, truncate: true, length: 50)
```

Which, AFAICT comes from `MakeMakefile::Logging.message` http://www.rubydoc.info/stdlib/mkmf/2.0.0/MakeMakefile/Logging

Does the library require use of `mkmf` in cucumber? https://github.com/mattheworiordan/capybara-screenshot/blob/14af3c1c094eacd67dd12c88be4029e06f407b07/lib/capybara-screenshot/cucumber.rb#L2

**Comment by mattheworiordan** [comment]
@arielvalentin sorry to hear that.  `mkmf` was introduced when `imgcat` support was added, see https://github.com/mattheworiordan/capybara-screenshot/commit/29d6f1b2aa75de8cbc2d344abad7912ef0b73be9.  However, looking at that commit now, it's not obvious why `mkmf` is needed at all. Have you tried just removing the `require` to see what happens?  I am going to ask the author of that commit why he included `mkmf`, but as far as I can tell, it is not needed...

**Comment by mattheworiordan** [comment]
FYI, I believe https://github.com/mattheworiordan/capybara-screenshot/commit/012208c093da6d98702a8ab2fec4bf4d68be79db fixes this issue now.  Pleas reopen if that is not the case.

**Comment by arielvalentin** [comment]
This fix works great!
