### ISSUE TITLE
zoom_factor method

### ISSUE THREAD

**Issue by connorshea** [mattheworiordan/capybara-screenshot#176]
I'm interested in taking automated screenshots for use in documentation for GitLab, and capybara-screenshot is currently a great option for that. My main problem is that it outputs screenshots that are visibly not-retina with font artifacting.

For example:
![image1](https://cloud.githubusercontent.com/assets/2977353/15803744/d9d2fadc-2aaa-11e6-96d3-66167ef8227b.png)

Poltergeist has [a page.zoomFactor method](https://github.com/teampoltergeist/poltergeist/pull/428) that can be used to zoom into a page, in effect creating the illusion of a retina display (e.g. set window_size to 2560, 1600 but zoom to 2). Would it be possible for capybara-screenshot to implement a zoom_factor method for this purpose?

If there are any other solutions you can point me to, that'd be greatly appreciated. I've been researching this but come up with nothing I could actually get working (except for using the JS API directly).

**Comment by connorshea** [comment]
For the record, the JS API using zoomFactor returns something like this, the difference is pretty obvious:

![gitlab](https://cloud.githubusercontent.com/assets/2977353/15803753/3f4c988c-2aab-11e6-91da-383b01f3d16e.png)

**Comment by mattheworiordan** [comment]
I don't believe this is what `capybara-screenshot` should be used for.  If you to automate screenshots simply call the methods to take a screenshot as and when you need it.  Also, this specific requirement is not something I believe we should be addressing, how you configure your drivers is up to you
