### ISSUE TITLE
Screenshot Saver fails when "page" is not the default Capybara session

### ISSUE THREAD

**Issue by ryanmcgarvey** [mattheworiordan/capybara-screenshot#180]
My tests use multiple active sessions (simulating multiple users interacting with each other in real time) - so I've gotten in the habit of instantiating my own Capybara::Session. As a result, I needed to override the default screenshot_and_save_page and screenshot_and_open_image methods to pass in my own session in lieu of the global Capybara.page.

The saver exits early since it checks for a current path from the global capybara reference, and not the page injected into the saver:

``` ruby
      def save
        # if current_path empty then nothing to screen shot as browser has not loaded any URL
        return if capybara.current_path.to_s.empty?

        save_html if @html_save
        save_screenshot
      end
```

**The solution, I believe, is to use the injected page object instead of the global reference. Thoughts?**

Pull request to follow.

Also: I think we might see the same problem in save_screenshot if one were to use a different driver in their session than is currently globally registered with capybara

``` ruby
      def save_screenshot
        path = screenshot_path
        clear_save_and_open_page_path do
          result = Capybara::Screenshot.registered_drivers.fetch(capybara.current_driver) { |driver_name|
            warn "capybara-screenshot could not detect a screenshot driver for '#{capybara.current_driver}'. Saving with default with unknown results."
            Capybara::Screenshot.registered_drivers[:default]
          }.call(page.driver, path)
          @screenshot_saved = result != :not_supported
        end
      end
```

**Comment by TylerRick** [comment]
Should this be closed? It looks like the associated PR, #181, has been merged, so I assume this is working/fixed now...
