### ISSUE TITLE
Bad interaction with Rails travel_to

### ISSUE THREAD

**Issue by md5** [mattheworiordan/capybara-screenshot#191]
When using the Rails `travel_to` helper to set the current time to a fixed value, the screenshots for `capybara-screenshot` are all timestamped with the same time. This causes multiple failures to overwrite each other's screenshots, not to mention making it confusing when a failure actually happened during the testing sequence.

**Comment by md5** [comment]
One way to work around this is to use custom filenames to avoid using the time in the name: https://github.com/mattheworiordan/capybara-screenshot#custom-screenshot-filename

**Comment by md5** [comment]
An easier approach might be to use `append_timestamp = false` and `append_random = true` (or just `append_random = true`).

**Comment by md5** [comment]
This looks like it's actually a duplicate of #112 and that `append_random` was meant to address this problem (in #113).

**Comment by joefreeman** [comment]
Here's another workaround if you really want timestamps:

```
Capybara::Screenshot.append_timestamp = false
Capybara::Screenshot.register_filename_prefix_formatter(:default) do |test|
  time_now = Time.__simple_stub__now
  timestamp = "#{time_now.strftime('%Y-%m-%d-%H-%M-%S.')}#{'%03d' % (time_now.usec/1000).to_i}"
  "screenshot_#{timestamp}"
end
```

Not really a fault of this project, but I guess it wouldn't hurt to try `Time.__simple_stub__now` first [here](https://github.com/mattheworiordan/capybara-screenshot/blob/fe47a6816677d573fd5428dae60a31bc8898f623/lib/capybara-screenshot/saver.rb#L16)?

**Comment by md5** [comment]
Seems like it should check `:respond_to?` first in case `Time.now` hasn't been stubbed in a particular test.
