### ISSUE TITLE
Only captures a small portion of some pages

### ISSUE THREAD

**Issue by zacharyjt** [mattheworiordan/capybara-screenshot#192]
Hello,

I'm running into an issue with capybara-screenshot where, on some pages, it only captures a small strip at the very top of the page.  Here is an example:

![screenshot_2016-10-31-15-01-27 727](https://cloud.githubusercontent.com/assets/3739104/19870218/04b783d0-9f86-11e6-8d72-b83e92f27998.png)

This only seems to happen on some pages, but I haven't figured out why.  The HTML capture is fine... it's just the image that is clipped.  We use Ember, and are generally a pretty js-heavy app... not sure if that might have something to do with it.  Any thoughts what might be happening here?

Thanks!

**Comment by SpyMaster356** [comment]
This is a known issue with capybara-webkit. Have a look under the driver configuration section in the README

**Comment by zacharyjt** [comment]
Forgot to come back and comment on this, but the driver configuration definitely solved my issue.  Thanks @SpyMaster356 !
