### ISSUE TITLE
Not working with rspec's aggregate_failures option

### ISSUE THREAD

**Issue by ypresto** [mattheworiordan/capybara-screenshot#216]
When failure happened in `it '...', aggregate_failures: true do` block, capybara-screenshot does not take any screenshot.

Library versions:

capybara (2.13.0)
capybara-screenshot (1.0.17)
rails (5.1.3)
rspec-core (3.5.4)
rspec-rails (3.5.2)

**Comment by mattheworiordan** [comment]
I believe this is fixed with https://github.com/mattheworiordan/capybara-screenshot/pull/213.  I will close this issue, but re-open if not.
