### ISSUE TITLE
warning about cucumber 5 logged every time screenshot generated

### ISSUE THREAD

**Issue by alan-giles-zesty** [mattheworiordan/capybara-screenshot#272]
WARNING: #embed(file, mime_type, label) is deprecated and will be removed after version 5.0.0. Please use attach(file, media_type) instead.
(Called from xxx/capybara-screenshot-1.0.24/lib/capybara-screenshot/cucumber.rb:24:in `block (2 levels) in <top (required)>')

**Comment by mattheworiordan** [comment]
This is now resolved, see https://github.com/mattheworiordan/capybara-screenshot/pull/274
