### ISSUE TITLE
Release version 1.0.25 to rubygems

### ISSUE THREAD

**Issue by BrianHawley** [mattheworiordan/capybara-screenshot#275]
The changelog and tags say that there is a version 1.0.25, but Rubygems doesn't have it yet.

**Comment by mattheworiordan** [comment]
Good point, thanks for highlighting, fixing now.

**Comment by mattheworiordan** [comment]
Done https://rubygems.org/gems/capybara-screenshot/versions/1.0.25, was caused by an OTP issue
