### ISSUE TITLE
how to emulate save_and_open_page

### ISSUE THREAD

**Issue by snoblenet** [mattheworiordan/capybara-screenshot#40]
Great work. How can we not only have it save the HTML on an error, but automatically open it, just like Capybara's save_and_open_page method?

**Comment by swrobel** [comment]
Thanks for the great gem. It would be awesome to have this functionality. I currently hacked it into my rspec setup in the following way:

```ruby
Capybara::Screenshot.autosave_on_failure = false

RSpec.configure do |config|
  config.after do |example|
    if example.metadata[:type] == :feature && example.exception.present?
      save_and_open_page
    end
  end
end
```

**Comment by mattheworiordan** [comment]
@swrobel fancy doing a PR to add this functionality?
