### ISSUE TITLE
open the screenshot upon failure

### ISSUE THREAD

**Issue by gvt** [mattheworiordan/capybara-screenshot#43]
When there is a failure and the screenshot is generated, I'd like to have the screenshot opened immediately in a viewer. Something like `open filename` would work on Mac. Where would I hook in to do this?

**Comment by mattheworiordan** [comment]
I am going to close this issue as unfortunately I am too busy right now to add this feature.  If anyone wants to issue a PR, I will gladly welcome this feature.
