### ISSUE TITLE
uninitialized constant Capybara::Screenshot

### ISSUE THREAD

**Issue by kostia** [mattheworiordan/capybara-screenshot#54]
Ruby-1.9, Capybara-1.1.4, Selenium-WebDriver-2.32.1

**Comment by nruth** [comment]
I had this problem when provisioning ubuntu 14 ruby 2.1 with brightbox's ruby PPA in vagrant, but it went away when I started using rbenv to install ruby instead.

**Comment by jkrmr** [comment]
I just saw this same behavior immediately after installing the gem. For the fix was restarting Spring:

```
bin/spring stop
bin/rspec
```
