### ISSUE TITLE
Update README to cover minitest ActionDispatch requirement

### ISSUE THREAD

**Issue by coderjoe** [mattheworiordan/capybara-screenshot#63]
It should be clarified in the README that capybara-screenshot/minitest has a hard dependency on ActionDispatch. This is important for those of us who are using capybara and minitest to integration test non-rails or 3rd party applications and thus aren't making use of Action::Dispatch::IntegrationTest.

**Comment by mattheworiordan** [comment]
I am going to close as this was not resolved.

**Comment by coderjoe** [comment]
Sounds good. Sorry for the long-standing bug with no PR. :)
