### ISSUE TITLE
No auto save on failure

### ISSUE THREAD

**Issue by gamov** [mattheworiordan/capybara-screenshot#97]
On my setup, the Saver never saves anything because of line https://github.com/mattheworiordan/capybara-screenshot/blob/master/lib/capybara-screenshot/saver.rb#L25 where capybara.current_path is always nil
I can use it manually but I don't really see the point…

* ruby-1.9.3-p545
* rails 3.0.20
* minitest 4.7.5

PS: is it possible to set the file names to <testfilename-testname-line>?

**Comment by mattheworiordan** [comment]
@gamov I am assuming this is no longer an issue so closing

**Comment by gamov** [comment]
it still is… but nvm.

**Comment by mattheworiordan** [comment]
Oh, sorry to hear.  I assume it's still a Zeus issue then?

**Comment by gamov** [comment]
Since I've been updating to Rails 4, I revisited this topic since no screenshots at all where saved now. It is simply because I call Capybara.reset_sessions! in a teardown hook and capybara-screenshot defines its in an after_teardown hook. I copied the code in my teardown hook and it works as advertised.
